In [1]:
import pandas as pd
import numpy as np
import warnings; warnings.filterwarnings('ignore')

In [2]:
movies = pd.read_csv('data/tmdb_5000_movies.csv')

In [3]:
print(movies.shape)
movies.head(1)

(4803, 20)


budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                      homepage     id  \
0  http://www.avatarmovie.com/  19995   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   

  original_title                                           overview  \
0         Avatar  In the 22nd century, a paraplegic Marine is di...   

   popularity                               production_companies  \
0  150.437577  [{"name": "Ingenious Film Partners", "id": 289...   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   

                       tagline   title  vote_average  vote_count  
0  Enter the World of Pandora.  Avatar           7.2       11800

In [4]:
movies_df= movies[['id','title','genres','vote_average','vote_count','popularity','keywords','overview']]
movies_df.head(5)

id                                     title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   
3   49026                     The Dark Knight Rises   
4   49529                               John Carter   

                                              genres  vote_average  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.3   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...           7.6   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.1   

   vote_count  popularity                                           keywords  \
0       11800  150.437577  [{"id": 1463, "name": "culture clash"}, {"id":...   
1        4500  139.082615  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2        4466  107.376788  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3        9106  112.312950  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4        2124   43.926995  [{"id": 818, "name": "based on novel"}, {"id":...   

                                            overview  
0  In the 22nd century, a paraplegic Marine is di...  
1  Captain Barbossa, long believed to be dead, ha...  
2  A cryptic message from Bond’s past sends him o...  
3  Following the death of District Attorney Harve...  
4  John Carter is a war-weary, former military ca...

In [7]:
movies_df['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [8]:
type(movies_df['genres'][0])
# str 타입인 것을 확인할 수 있다.

str

### genres, keywords 칼럼들의 str형태를 list형태로 바꿔주기

In [9]:
from ast import literal_eval  # 문자열 파싱 라이브러리

movies_df['genres'] = movies_df['genres'].apply(literal_eval)
movies_df['keywords'] = movies_df['keywords'].apply(literal_eval)

In [10]:
movies_df['genres'][0]

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [11]:
type(movies_df['genres'][0])
# str타입에서 list타입으로 바뀐 것을 확인할 수 있다.

list

### list 내 여러개 딕셔너리의 name키에 해당하는 값들을 리스트로 변환

In [12]:
movies_df['genres'] = movies_df['genres'].apply(lambda x : [ y['name'] for y in x])
movies_df['keywords'] = movies_df['keywords'].apply(lambda x : [ y['name'] for y in x])

In [13]:
movies_df[['genres', 'keywords']][:1]

genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   

                                            keywords  
0  [culture clash, future, space war, space colon...

## -> 데이터 전처리 끝

## 장르 컨텐츠 유사도 측정

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
# 참고 : CountVectorizer에 대하여
# CountVectorizer는 다음 세가지를 수행한다.
# 1. 문서를 토큰 리스트로 변환한다.
# 2. 각 문서에서 토큰의 출현 빈도를 센다.
# 3. 각 문서를 BOW(Bag of Words) 인코딩 벡터로 변환한다.

from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
    'The last document?',
]
vect = CountVectorizer()
vect.fit(corpus)
vect.vocabulary_

{'this': 9,
 'is': 3,
 'the': 7,
 'first': 2,
 'document': 1,
 'second': 6,
 'and': 0,
 'third': 8,
 'one': 5,
 'last': 4}

In [22]:
movies_df['genres']

0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...                      
4798                        [Action, Crime, Thriller]
4799                                [Comedy, Romance]
4800               [Comedy, Drama, Romance, TV Movie]
4801                                               []
4802                                    [Documentary]
Name: genres, Length: 4803, dtype: object

In [23]:
# CountVectorizer를 적용하기 위해 공백문자로 word 단위가 구분되는 문자열로 변환. 
movies_df['genres_literal'] = movies_df['genres'].apply(lambda x : (' ').join(x))
movies_df['genres_literal']

0       Action Adventure Fantasy Science Fiction
1                       Adventure Fantasy Action
2                         Action Adventure Crime
3                    Action Crime Drama Thriller
4               Action Adventure Science Fiction
                          ...                   
4798                       Action Crime Thriller
4799                              Comedy Romance
4800               Comedy Drama Romance TV Movie
4801                                            
4802                                 Documentary
Name: genres_literal, Length: 4803, dtype: object

In [24]:
# CountVectorizer로 학습시켰더니 4803개 영화에 대한 276개 장르의 '장르 매트릭스'가 생성되었다.
count_vect = CountVectorizer(min_df=0, ngram_range=(1, 2)) #min_df: 단어장에 들어갈 최소빈도, ngram_range: 1 <= n <= 2
genre_mat = count_vect.fit_transform(movies_df['genres_literal'])
print(genre_mat.shape)

(4803, 276)


In [25]:
print(genre_mat)

  (0, 0)	1
  (0, 16)	1
  (0, 124)	1
  (0, 232)	1
  (0, 138)	1
  (0, 1)	1
  (0, 24)	1
  (0, 135)	1
  (0, 233)	1
  (1, 0)	1
  (1, 16)	1
  (1, 124)	1
  (1, 24)	1
  (1, 125)	1
  (2, 0)	1
  (2, 16)	1
  (2, 1)	1
  (2, 64)	1
  (2, 20)	1
  (3, 0)	1
  (3, 64)	1
  (3, 90)	1
  (3, 234)	1
  (3, 4)	1
  (3, 68)	1
  :	:
  (4796, 90)	1
  (4796, 234)	1
  (4796, 106)	1
  (4796, 144)	1
  (4797, 234)	1
  (4797, 153)	1
  (4797, 157)	1
  (4798, 0)	1
  (4798, 64)	1
  (4798, 234)	1
  (4798, 4)	1
  (4798, 78)	1
  (4799, 44)	1
  (4799, 214)	1
  (4799, 58)	1
  (4800, 90)	1
  (4800, 44)	1
  (4800, 214)	1
  (4800, 104)	1
  (4800, 50)	1
  (4800, 250)	1
  (4800, 182)	1
  (4800, 251)	1
  (4800, 229)	1
  (4802, 80)	1


In [26]:
# CountVectorizer로 학습시켰더니 4803개 영화에 대한 22개 장르의 '장르 매트릭스'가 생성되었다.
count_vect2 = CountVectorizer(min_df=1, ngram_range=(1,1)) #min_df: 단어장에 들어갈 최소빈도, ngram_range: 1 <= n <= 2
genre_mat2 = count_vect2.fit_transform(movies_df['genres_literal'])
print(genre_mat2.shape)

(4803, 22)


In [27]:
print(genre_mat2)

  (0, 0)	1
  (0, 1)	1
  (0, 8)	1
  (0, 17)	1
  (0, 9)	1
  (1, 0)	1
  (1, 1)	1
  (1, 8)	1
  (2, 0)	1
  (2, 1)	1
  (2, 4)	1
  (3, 0)	1
  (3, 4)	1
  (3, 6)	1
  (3, 18)	1
  (4, 0)	1
  (4, 1)	1
  (4, 17)	1
  (4, 9)	1
  (5, 0)	1
  (5, 1)	1
  (5, 8)	1
  (6, 2)	1
  (6, 7)	1
  (7, 0)	1
  :	:
  (4792, 18)	1
  (4792, 12)	1
  (4792, 15)	1
  (4793, 6)	1
  (4794, 18)	1
  (4794, 3)	1
  (4794, 12)	1
  (4795, 6)	1
  (4796, 17)	1
  (4796, 9)	1
  (4796, 6)	1
  (4796, 18)	1
  (4797, 18)	1
  (4797, 10)	1
  (4798, 0)	1
  (4798, 4)	1
  (4798, 18)	1
  (4799, 3)	1
  (4799, 16)	1
  (4800, 6)	1
  (4800, 3)	1
  (4800, 16)	1
  (4800, 19)	1
  (4800, 13)	1
  (4802, 5)	1


In [30]:
# CountVectorizer로 학습시켰더니 4803개 영화에 대한 276개 장르의 '장르 매트릭스'가 생성되었다.
count_vect2 = CountVectorizer(min_df=0, ngram_range=(1,1)) #min_df: 단어장에 들어갈 최소빈도, ngram_range: 1 <= n <= 2
genre_mat2 = count_vect2.fit_transform(movies_df['genres_literal'])
print(genre_mat2.shape)

(4803, 22)


### 코사인 유사도(cosine_similarity)이용해서 영화별 유사도 계산

In [31]:
# 코사인 유사도에 의해 4803개 영화 각각 유사한 영화들이 계산됨
from sklearn.metrics.pairwise import cosine_similarity
genre_sim = cosine_similarity(genre_mat, genre_mat)
print(genre_sim.shape)
print(genre_sim[:5])

(4803, 4803)
[[1.         0.59628479 0.4472136  ... 0.         0.         0.        ]
 [0.59628479 1.         0.4        ... 0.         0.         0.        ]
 [0.4472136  0.4        1.         ... 0.         0.         0.        ]
 [0.12598816 0.16903085 0.3380617  ... 0.12598816 0.         0.        ]
 [0.75592895 0.3380617  0.50709255 ... 0.         0.         0.        ]]


In [32]:
# 자료를 정렬하는 것이 아니라 순서만 알고 싶다면 argsort
# 유사도가 높은 영화를 앞에서부터 순서대로 보여줌
# 0번째 영화의 경우 유사도 순서 : 0번, 3494번, 813번, ..., 2401 순서
genre_sim_sorted_ind = genre_sim.argsort()[:, ::-1] # 전체를 -1칸 간격으로
print(genre_sim_sorted_ind[:1])

[[   0 3494  813 ... 3038 3037 2401]]


In [33]:
genre_sim_sorted_ind

array([[   0, 3494,  813, ..., 3038, 3037, 2401],
       [ 262,    1,  129, ..., 3069, 3067, 2401],
       [   2, 1740, 1542, ..., 3000, 2999, 2401],
       ...,
       [4800, 3809, 1895, ..., 2229, 2230,    0],
       [4802, 1594, 1596, ..., 3204, 3205,    0],
       [4802, 4710, 4521, ..., 3140, 3141,    0]], dtype=int64)

## 추천 ver1. 장르 코사인 유사도에 의해 영화를 추천하는 함수

### 함수 분석

In [34]:
# 인자로 입력된 movies_df DataFrame에서 'title' 컬럼이 입력된 title_name 값인 DataFrame추출
title_movie = movies_df[movies_df['title'] == 'The Godfather']
title_movie

id          title          genres  vote_average  vote_count  \
3337  238  The Godfather  [Drama, Crime]           8.4        5893   

      popularity                                           keywords  \
3337  143.659698  [italy, love at first sight, loss of father, p...   

                                               overview genres_literal  
3337  Spanning the years 1945 to 1955, a chronicle o...    Drama Crime

In [35]:
# title_named을 가진 DataFrame의 index 객체를 ndarray로 반환하고 
# sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n 개의 index 추출
title_index = title_movie.index.values
title_index

array([3337], dtype=int64)

In [36]:
similar_indexes = genre_sim_sorted_ind[title_index, :10]
similar_indexes

array([[2731, 1243, 3636, 1946, 2640, 4065, 1847, 4217,  883, 3866]],
      dtype=int64)

In [37]:
# 추출된 top_n index들 출력. top_n index는 2차원 데이터 임.
# dataframe에서 index로 사용하기 위해서 2차원 array를 1차원 array로 변경
similar_indexes = similar_indexes.reshape(-1)
print(similar_indexes)

[2731 1243 3636 1946 2640 4065 1847 4217  883 3866]


In [38]:
movies_df.iloc[similar_indexes]

id                                           title          genres  \
2731     240                          The Godfather: Part II  [Drama, Crime]   
1243     203                                    Mean Streets  [Drama, Crime]   
3636   36351                                   Light Sleeper  [Drama, Crime]   
1946   11699  The Bad Lieutenant: Port of Call - New Orleans  [Drama, Crime]   
2640     400         Things to Do in Denver When You're Dead  [Drama, Crime]   
4065  364083                                      Mi America  [Drama, Crime]   
1847     769                                      GoodFellas  [Drama, Crime]   
4217    9344                                            Kids  [Drama, Crime]   
883      640                             Catch Me If You Can  [Drama, Crime]   
3866     598                                     City of God  [Drama, Crime]   

      vote_average  vote_count  popularity  \
2731           8.3        3338  105.792936   
1243           7.2         345   17.002096   
3636           5.7          15    6.063868   
1946           6.0         326   17.339852   
2640           6.7          85    6.932221   
4065           0.0           0    0.039007   
1847           8.2        3128   63.654244   
4217           6.8         279   13.291991   
883            7.7        3795   73.944049   
3866           8.1        1814   44.356711   

                                               keywords  \
2731  [italo-american, cuba, vororte, melancholy, pr...   
1243  [epilepsy, protection money, secret love, mone...   
3636  [suicide, drug dealer, redemption, addict, exi...   
1946  [police brutality, organized crime, policeman,...   
2640  [father son relationship, bounty hunter, boat,...   
4065                       [new york state, hate crime]   
1847  [prison, based on novel, florida, 1970s, mass ...   
4217                              [puberty, first time]   
883   [con man, biography, fbi agent, overhead camer...   
3866  [male nudity, street gang, brazilian, photogra...   

                                               overview genres_literal  
2731  In the continuing saga of the Corleone crime f...    Drama Crime  
1243  A small-time hood must choose from among love,...    Drama Crime  
3636  A drug dealer with upscale clientele is having...    Drama Crime  
1946  Terrence McDonagh, a New Orleans Police sergea...    Drama Crime  
2640  A mafia film in Tarantino style with a star-st...    Drama Crime  
4065  A hate-crime has been committed in a the small...    Drama Crime  
1847  The true story of Henry Hill, a half-Irish, ha...    Drama Crime  
4217  A controversial portrayal of teens in New York...    Drama Crime  
883   A true story about Frank Abagnale Jr. who, bef...    Drama Crime  
3866  Cidade de Deus is a shantytown that started du...    Drama Crime

### 실제 함수

In [39]:
def find_sim_movie_ver1(df, sorted_ind, title_name, top_n=10):
    
    # 인자로 입력된 movies_df DataFrame에서 'title' 컬럼이 입력된 title_name 값인 DataFrame추출
    title_movie = df[df['title'] == title_name]
    
    # title_named을 가진 DataFrame의 index 객체를 ndarray로 반환하고 
    # sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n 개의 index 추출
    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index, :(top_n)]
    
    # 추출된 top_n index들 출력. top_n index는 2차원 데이터 임.
    # dataframe에서 index로 사용하기 위해서 1차원 array로 변경
    print(similar_indexes)    
    # 2차원 데이터를 1차원으로 변환
    similar_indexes = similar_indexes.reshape(-1)
    
    return df.iloc[similar_indexes]

### 영화 Gotfather와 장르가 유사한 영화 10개 추천

In [40]:
similar_movies = find_sim_movie_ver1(movies_df, genre_sim_sorted_ind, 'The Godfather',10)
similar_movies[['title', 'vote_average', 'genres', 'vote_count']]
# 문제 ; 평점 기반으로 추천하고자 하는데, vote_count가 낮은 영화는 제외하고 싶음

[[2731 1243 3636 1946 2640 4065 1847 4217  883 3866]]


title  vote_average  \
2731                          The Godfather: Part II           8.3   
1243                                    Mean Streets           7.2   
3636                                   Light Sleeper           5.7   
1946  The Bad Lieutenant: Port of Call - New Orleans           6.0   
2640         Things to Do in Denver When You're Dead           6.7   
4065                                      Mi America           0.0   
1847                                      GoodFellas           8.2   
4217                                            Kids           6.8   
883                              Catch Me If You Can           7.7   
3866                                     City of God           8.1   

              genres  vote_count  
2731  [Drama, Crime]        3338  
1243  [Drama, Crime]         345  
3636  [Drama, Crime]          15  
1946  [Drama, Crime]         326  
2640  [Drama, Crime]          85  
4065  [Drama, Crime]           0  
1847  [Drama, Crime]        3128  
4217  [Drama, Crime]         279  
883   [Drama, Crime]        3795  
3866  [Drama, Crime]        1814

In [41]:
# 평점 기준으로 정렬(sort_values)해보니 평가횟수(vote_count)가 낮은 것들도 포함됨. 평가횟수 반영한 평점(가중평점)이 필요함
movies_df[['title','vote_average','vote_count']].sort_values('vote_average', ascending=False)[:10]

title  vote_average  vote_count
3519          Stiff Upper Lips          10.0           1
4247     Me You and Five Bucks          10.0           2
4045     Dancer, Texas Pop. 81          10.0           1
4662            Little Big Top          10.0           1
3992                 Sardaarji           9.5           2
2386            One Man's Hero           9.3           2
2970        There Goes My Baby           8.5           2
1881  The Shawshank Redemption           8.5        8205
2796     The Prisoner of Zenda           8.4          11
3337             The Godfather           8.4        5893

## 가중평점(평점&평가횟수) 반영한 영화 추천

In [42]:
# 상위 60%에 해당하는 vote_count를 최소 투표 횟수인 m으로 지정
C = movies_df['vote_average'].mean()
m = movies_df['vote_count'].quantile(0.6)

In [43]:
# C: 전체 영화에 대한 평균평점 = 약 6점
# m: 평점을 부여하기 위한 최소 투표 횟수 = 370회(상위 60% 수준)
print('C:',round(C,3), 'm:',round(m,3))

C: 6.092 m: 370.2


### 가중평점을 계산하는 함수

In [44]:
def weighted_vote_average(record):
    v = record['vote_count']
    R = record['vote_average']
    
    return ( (v/(v+m)) * R ) + ( (m/(m+v)) * C )   

In [45]:
# 기존 데이터에 가중평점 칼럼 추가
movies_df['weighted_vote'] = movies_df.apply(weighted_vote_average, axis=1)

In [46]:
# 가중평점(weighted_vote) 기준으로 영화 순위 뽑아보기
movies_df[['weighted_vote','title','vote_average','vote_count','genres']].sort_values('weighted_vote', ascending=False)[:10]

weighted_vote                     title  vote_average  vote_count  \
1881       8.396052  The Shawshank Redemption           8.5        8205   
3337       8.263591             The Godfather           8.4        5893   
662        8.216455                Fight Club           8.3        9413   
3232       8.207102              Pulp Fiction           8.3        8428   
65         8.136930           The Dark Knight           8.2       12002   
1818       8.126069          Schindler's List           8.3        4329   
3865       8.123248                  Whiplash           8.3        4254   
809        8.105954              Forrest Gump           8.2        7927   
2294       8.105867             Spirited Away           8.3        3840   
2731       8.079586    The Godfather: Part II           8.3        3338   

                                       genres  
1881                           [Drama, Crime]  
3337                           [Drama, Crime]  
662                                   [Drama]  
3232                        [Thriller, Crime]  
65           [Drama, Action, Crime, Thriller]  
1818                    [Drama, History, War]  
3865                                  [Drama]  
809                  [Comedy, Drama, Romance]  
2294  [Fantasy, Adventure, Animation, Family]  
2731                           [Drama, Crime]

## 추천 ver2. 먼저 장르 유사성 높은 영화 20개 선정 후, 가중평점순 10개 선정

In [47]:
def find_sim_movie_ver2(df, sorted_ind, title_name, top_n=10):
    title_movie = df[df['title'] == title_name]
    title_index = title_movie.index.values
    
    # top_n의 2배에 해당하는 쟝르 유사성이 높은 index 추출
    similar_indexes = sorted_ind[title_index, :(top_n*2)]
    similar_indexes = similar_indexes.reshape(-1)

    # 기준 영화 index는 제외
    similar_indexes = similar_indexes[similar_indexes != title_index]
    
    # top_n의 2배에 해당하는 후보군에서 weighted_vote 높은 순으로 top_n 만큼 추출 
    return df.iloc[similar_indexes].sort_values('weighted_vote', ascending=False)[:top_n]

### 영화 Gotfather에 대해 장르 유사성, 가중평점 반영한 추천 영화 10개를 뽑아보자

In [48]:
similar_movies = find_sim_movie_ver2(movies_df, genre_sim_sorted_ind, 'The Godfather',10)
similar_movies[['title', 'vote_average', 'weighted_vote', 'genres', 'vote_count']]

title  vote_average  weighted_vote  \
2731       The Godfather: Part II           8.3       8.079586   
1847                   GoodFellas           8.2       7.976937   
3866                  City of God           8.1       7.759693   
1663  Once Upon a Time in America           8.2       7.657811   
883           Catch Me If You Can           7.7       7.557097   
281             American Gangster           7.4       7.141396   
4041              This Is England           7.4       6.739664   
1149              American Hustle           6.8       6.717525   
1243                 Mean Streets           7.2       6.626569   
2839                     Rounders           6.9       6.530427   

              genres  vote_count  
2731  [Drama, Crime]        3338  
1847  [Drama, Crime]        3128  
3866  [Drama, Crime]        1814  
1663  [Drama, Crime]        1069  
883   [Drama, Crime]        3795  
281   [Drama, Crime]        1502  
4041  [Drama, Crime]         363  
1149  [Drama, Crime]        2807  
1243  [Drama, Crime]         345  
2839  [Drama, Crime]         439

## 요약 : Gotfather를 좋아하는 사람에게 영화 추천해주기

### 응용 : Spider-Man 3 좋아하는 사람 기준으로 장르가 유사한 영화를 추천해주자

In [49]:
similar_movies = find_sim_movie_ver2(movies_df, genre_sim_sorted_ind, 'Spider-Man 3',10)
similar_movies[['title', 'vote_average', 'weighted_vote', 'genres', 'vote_count']]

title  vote_average  \
329      The Lord of the Rings: The Return of the King           8.1   
262  The Lord of the Rings: The Fellowship of the Ring           8.0   
330              The Lord of the Rings: The Two Towers           8.0   
19           The Hobbit: The Battle of the Five Armies           7.1   
98                   The Hobbit: An Unexpected Journey           7.0   
126                               Thor: The Dark World           6.8   
30                                        Spider-Man 2           6.7   
129                                               Thor           6.6   
20                              The Amazing Spider-Man           6.5   
38                            The Amazing Spider-Man 2           6.5   

     weighted_vote                        genres  vote_count  
329       8.011871  [Adventure, Fantasy, Action]        8064  
262       7.922175  [Adventure, Fantasy, Action]        8705  
330       7.910111  [Adventure, Fantasy, Action]        7487  
19        7.027274  [Action, Adventure, Fantasy]        4760  
98        6.961224  [Adventure, Fantasy, Action]        8297  
126       6.748873  [Action, Adventure, Fantasy]        4755  
30        6.652034  [Action, Adventure, Fantasy]        4321  
129       6.572735  [Adventure, Fantasy, Action]        6525  
20        6.478296  [Action, Adventure, Fantasy]        6586  
38        6.466812  [Action, Adventure, Fantasy]        4179

### 응용 : Enemy at the Gates 좋아하는 사람 기준으로 장르가 유사한 영화를 추천해주자

In [50]:
similar_movies = find_sim_movie_ver2(movies_df, genre_sim_sorted_ind, 'Enemy at the Gates',10)
similar_movies[['title', 'vote_average', 'weighted_vote', 'genres', 'vote_count']]

title  vote_average  weighted_vote  \
1525                  Apocalypse Now           8.0       7.708775   
2798  The Boy in the Striped Pyjamas           7.7       7.373173   
2536                 The Deer Hunter           7.8       7.310348   
1662                           Glory           7.4       6.757199   
585                        War Horse           7.0       6.753283   
2662                     Sarah's Key           7.2       6.475666   
2016               The Water Diviner           6.8       6.472943   
557                          Jarhead           6.6       6.434392   
2671      Born on the Fourth of July           6.7       6.405936   
3310                    Far from Men           6.6       6.145019   

            genres  vote_count  
1525  [Drama, War]        2055  
2798  [War, Drama]        1451  
2536  [Drama, War]         921  
1662         [War]         383  
585   [Drama, War]         992  
2662  [Drama, War]         196  
2016  [War, Drama]         431  
557   [Drama, War]         765  
2671  [Drama, War]         395  
3310  [Drama, War]          43